name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-git-messages:
    name: Commits
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@ed7b4827feafc644f1fd1b723b7a1ca890480009 # main

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      php-versions: '["8.4"]'
